services:
  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - ./src:/app
    restart: on-failure:3
    networks:
      - web

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_DB=testedb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testemercos
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    networks:
      - web
    volumes:
      - postgres_data:/var/lib/postgresql/data

  streamlit:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: streamlit_app
    volumes:
      - ./frontend:/app
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - web

networks:
  web:
    driver: bridge

volumes:
  postgres_data:
